# Generated by Django 5.0.7 on 2025-07-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_sublecturequiz_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='course_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='transaction',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
