# Generated by Django 5.0.7 on 2025-07-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_usercourse_course_price_usercourse_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizchoice',
            name='choice',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
